### ISSUE TITLE
Concerning behaviour.

### ISSUE THREAD

**Issue by Sin-Shadow-Fox** [i486/VxKex#41]
So i opened an issue with VxKex a while back about VxKex being unsafe for use. I attached a list of standards to meet to be considered safe for use and recently that issue was closed with a very concerning "Not-planned". This has me very concerned about the ethicacy of this program and the people who made it. I can only think of one reason why someone would intentionally not want to comply with safety regulations, and it isn't pleasant. I'm hoping this was either an error of automation or was accidentally marked as "Not-planned" but was instead fixed and is now complaint with virus definitions standard of safety. Either way I'm hoping for an explanation for the closer to put my mind, and the minds of others, at ease.

Original issue: https://github.com/i486/VxKex/issues/26

**Comment by i486** [comment]
VxKex employs certain advanced techniques such as Image File Execution Options (IFEO), which is a legitimate Windows debugging mechanism. IFEO allows developers to intercept and modify how specific programs execute. While this is a powerful tool for enhancing compatibility and debugging, it is worth noting that many malware also leverages IFEO for malicious purposes, such as redirecting processes or injecting malicious code. Because of this, antivirus (AV) software often flags applications using IFEO or similar techniques as potentially harmful. This is not an inherent indication of malicious intent but rather a side effect of the way these tools are used and monitored.

To assure you, all installers and source codes uploaded in this repository are genuine and untouched files (see note below) directly from the original author. If you have concerns regarding AV detections with the installer, you are welcome to compile it directly from the source code. I was able to compile it myself in under 10 minutes, despite not being a developer, which shows that the process is straightforward and accessible for anyone. 

_Note: the link references have been updated from https://github.com/vxiiduu/VxKex to https://github.com/i486/VxKex/ in recently released VxKex 1.1.2.1428 installers to prevent directing traffic to the impersonator._

**Comment by CommonLoon102** [comment]
You don't trust an open-source program, but you trust Microsoft and install Windows 7 which is closed-source and you will never know what it is doing.

Logic.

**Comment by Sin-Shadow-Fox** [comment]
> You don't trust an open-source program, but you trust Microsoft and install Windows 7 which is closed-source and you will never know what it is doing.
> 
> Logic.

Ah, nice to have the resident troll back. Typical troll logic "if i say a bunch of incorrect stuff confidently enough, i'll win" lol. I never said i trust microsoft and the fact that i have windows 7 instead of 8/10/11 kinda shows that. Also i've put a lot of work into win7 to make it safe and yes i DO know what it's doing, nice try asshole.

**Comment by Templayer** [comment]
> > You don't trust an open-source program, but you trust Microsoft and install Windows 7 which is closed-source and you will never know what it is doing.
> > Logic.
> 
> Ah, nice to have the resident troll back. Typical troll logic "if i say a bunch of incorrect stuff confidently enough, i'll win" lol. I never said i trust microsoft and the fact that i have windows 7 instead of 8/10/11 kinda shows that. Also i've put a lot of work into win7 to make it safe and yes i DO know what it's doing, nice try asshole.
> 
> Also if you just trust anything open-source just because it's open-source then I'm surprised you haven't caught any malware yet lol.

You seem to be the troll here. Using "lol" everywhere like a twelve-year-old kid.

open-source applications tend not to have malware, as it is trivial to check for it in the source code.

**Comment by Sin-Shadow-Fox** [comment]
> > > You don't trust an open-source program, but you trust Microsoft and install Windows 7 which is closed-source and you will never know what it is doing.
> > > Logic.
> > 
> > 
> > Ah, nice to have the resident troll back. Typical troll logic "if i say a bunch of incorrect stuff confidently enough, i'll win" lol. I never said i trust microsoft and the fact that i have windows 7 instead of 8/10/11 kinda shows that. Also i've put a lot of work into win7 to make it safe and yes i DO know what it's doing, nice try asshole.
> > Also if you just trust anything open-source just because it's open-source then I'm surprised you haven't caught any malware yet lol.
> 
> You seem to be the troll here. Using "lol" everywhere like a twelve-year-old kid.

Yeah sorry, that whole victim blaming thing ain't going to work here, nice try lol.

> open-source applications tend not to have malware, as it is trivial to check for it in the source code.

Open-source applications aren't regulated so they can have just about anything in them. Again, nice try troll.

When i get word back from Avast about the information that [i486](https://github.com/i486) provided, we'll see if it's clean or not.

**Comment by ahahahaah** [comment]
> > > You don't trust an open-source program, but you trust Microsoft and install Windows 7 which is closed-source and you will never know what it is doing.
> > > Logic.
> > 
> > 
> > Ah, nice to have the resident troll back. Typical troll logic "if i say a bunch of incorrect stuff confidently enough, i'll win" lol. I never said i trust microsoft and the fact that i have windows 7 instead of 8/10/11 kinda shows that. Also i've put a lot of work into win7 to make it safe and yes i DO know what it's doing, nice try asshole.
> > Also if you just trust anything open-source just because it's open-source then I'm surprised you haven't caught any malware yet lol.
> 
> You seem to be the troll here. Using "lol" everywhere like a twelve-year-old kid.

Do you judge the coherence of an argument based on the presence or absence of the word "lol"? lol
 
> open-source applications tend not to have malware,

tend not to = it can never happen?

>  as it is trivial to check for it in the source code.

ok, so have you really analysed the code yourself or have we to stay at the level "everybody can check the code so i admit its clean".

**Comment by Templayer** [comment]
> > > > You don't trust an open-source program, but you trust Microsoft and install Windows 7 which is closed-source and you will never know what it is doing.
> > > > Logic.
> > > 
> > > 
> > > Ah, nice to have the resident troll back. Typical troll logic "if i say a bunch of incorrect stuff confidently enough, i'll win" lol. I never said i trust microsoft and the fact that i have windows 7 instead of 8/10/11 kinda shows that. Also i've put a lot of work into win7 to make it safe and yes i DO know what it's doing, nice try asshole.
> > > Also if you just trust anything open-source just because it's open-source then I'm surprised you haven't caught any malware yet lol.
> > 
> > 
> > You seem to be the troll here. Using "lol" everywhere like a twelve-year-old kid.
> 
> Yeah sorry, that whole victim blaming thing ain't going to work here, nice try lol.
> 
> Edit: Btw, thanks for referencing this issue in a bunch of other posts. Now i can see how much of a troll [CommonLoon102](https://github.com/CommonLoon102) has been to other people as well.
> 
> > open-source applications tend not to have malware, as it is trivial to check for it in the source code.
> 
> Open-source applications aren't regulated so they can have just about anything in them. Again, nice try troll.
> 
> When i get word back from Avast about the information that [i486](https://github.com/i486) provided, we'll see if it's clean or not.

Nice job spamming everywhere your stupid bullshit. That is why you are a troll. Not because of your use of "lol" - that is why I called you a twelve-year-old. Or somebody with the mental capacity of one.

Also, you are calling everyone that contradicts you a troll. Maybe you should check the dictionary.

Please, go perish in a ditch.

Avast is one of the worst antiviruses on the planet. You must be really retarded to trust them. Their **opinion** is irrelevant and has literally no power over this software, or this repo. As do you, kid.

**Comment by Squall-Leonhart** [comment]
It's clean, there are no trojan behaviors such as rogue connections to unidentified servers, it only does what has been claimed.

**Comment by Sin-Shadow-Fox** [comment]
> It's clean, there are no trojan behaviors such as rogue connections to unidentified servers, it only does what has been claimed.

I hope so but i'd rather be safe. It should only be a few days to get a response from Avast.

> I don't know why i'm getting notifications for this issue though

That's . . . odd. You only get notified if you're @ed or you've already posted here so you shouldn't have been notified.
